const products = [
    {
        id: 1,
        name: 'Kacamata Wanita',
        class: 'womanGlasses',
        model: 'assets/womanglasses',
        desc: 'Kacamata dengan desain cat eye yang elegan dan feminin, memberikan kesan stylish dan modern. Bentuknya yang unik mampu menonjolkan fitur wajah, serta nyaman digunakan untuk berbagai aktivitas, baik santai maupun formal.',
        shortdesc: "Frame cat eye yang elegan dan feminim",
        img: 'womanglasses',
        tipe: 'Cat Eye Frame',
        jk: 'Wanita',
        fungsi: 'Fashion',
        berat: 'Ringan',
        bentuk: ['Oval', 'Bulat'],
        gaya: 'Elegan & Feminine'
    },
    {
        id: 2,
        name: 'Kacamata Pria',
        class: 'manGlasses',
        model: 'assets/manglasses',
        desc: 'Frame kacamata dengan desain kotak yang modern dan minimalis. Dilengkapi dengan struktur full frame yang kokoh serta ringan saat digunakan, sehingga memberikan kenyamanan untuk pemakaian sehari-hari. Cocok digunakan untuk berbagai aktivitas, baik formal maupun kasual.',
        shortdesc: "Frame kacamata dengan desain kotak",
        img: 'manglasses',
        tipe: 'Rectangular / Square Frame',
        jk: 'Pria',
        fungsi: 'Fashion',
        berat: 'Ringan',
        bentuk: ['Oval', 'Bulat'],
        gaya: 'Maskulin & Modern'
    },
    {
        id: 3,
        name: 'Kacamata Baca',
        class: 'readingGlasses',
        model: 'assets/readingglasses',
        desc: 'Kacamata baca dengan desain kotak yang simpel dan modern, dirancang untuk memberikan kenyamanan saat membaca atau bekerja dalam jarak dekat. Frame ringan dan ergonomis membantu mengurangi kelelahan mata, sehingga cocok digunakan dalam aktivitas sehari-hari seperti membaca buku, bekerja di depan komputer, atau menggunakan gadget.',
        shortdesc: "Kacamata dengan desain simpel dan modern",
        img: 'readingglasses',
        tipe: 'Full Frame (Square)',
        jk: 'Unisex',
        fungsi: 'Reading',
        berat: 'Ringan',
        bentuk: ['Oval', 'Bulat'],
        gaya: 'Simpel & Fungsional'
    },
    {
        id: 4,
        name: 'Kacamata Hitam',
        class: 'sunGlasses',
        model: 'assets/sunglasses',
        desc: 'Kacamata hitam dengan desain modern yang stylish dan fungsional, dirancang untuk melindungi mata dari paparan sinar matahari sekaligus menunjang penampilan. Frame ringan dan nyaman digunakan, cocok untuk aktivitas luar ruangan seperti berkendara, berlibur, maupun kegiatan santai.',
        shortdesc: "Kacamata dengan UV protection",
        img: 'sunglasses',
        tipe: '-',
        jk: 'Unisex',
        fungsi: 'UV Protection',
        berat: 'Ringan',
        bentuk: ['Oval', 'Bulat', 'Hati'],
        gaya: 'Stylish & Trendy'
    },
    {
        id: 5,
        name: 'Kacamata Olahraga',
        class: 'sportGlasses',
        model: 'assets/sportglasses',
        desc: 'Kacamata olahraga dengan desain ergonomis dan dinamis, dirancang untuk memberikan kenyamanan dan kestabilan saat beraktivitas. Frame ringan dan kokoh membantu melindungi mata dari angin, debu, dan sinar matahari, sehingga cocok digunakan untuk berbagai kegiatan outdoor seperti berlari, bersepeda, dan olahraga lainnya.',
        shortdesc: "Kacamata desain ergonomis dan dinamis",
        img: 'sportglasses',
        tipe: 'Wraparound Frame',
        jk: 'Unisex',
        fungsi: 'Sport',
        berat: 'Sangat Ringan',
        bentuk: ['Oval', 'Bulat', 'Persegi'],
        gaya: 'Sporty & Dinamis'
    },
];